---
title: ""
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---

### Graduate Supervison

#### Current Students {.tabset .tabset-fade .tabset-pills}

##### Ph.D Candidate

+ Lan Wu, PGRS Funded, Jointly with Dr. Jinjun Ran, 2025 - present
+ Yiliang Zhou, PGRS Funded, Jointly with Prof. N. Balakrishnan, 2024 - present
+ Jiahao Zhao, PGRS Funded, Jointly with Prof. Kaizhu Huang, 2024 - present


##### M.Sc. Candidate

+ Wenhuan He, Msc Actuarial Science,  2024
+ Junyuan Wu, Msc Actuarial Science,  2024
+ Tiancheng Li, Msc Data Science, 2024
+ Yanda Jiang, Msc Data Science, 2024

#### Past Students

+ Chenxia Liu, Msc Financial Mathematics,  2023
+ Pengyun Zhao, Msc Actuarial Science,  2023
+ Lan Wu, Msc Actuarial Science,  2023
+ Zhelin Wang, Msc Actuarial Science,  2022

### Undergraduate Supervison

#### Final Year Project 

At Xi'an Jiaotong-Liverpool University, each student gets an individual topic on which he/she works in the final year project for two semesters in close collaboration with a personal supervisor. The different projects and advisors are allocated at the beginning of the academic year. 

Within each project, each student works on a (small) research topic and produces a thesis and a presentation about the topic and his/her findings. In some projects the focus may be on literature studies and on the combination of information in scientific papers. In some other projects, the evaluation of statistics or writing small computer
programs may be required. Sometimes, the usage of computer algebra programs may be suitable. There is a wide variety of topics and research questions. In all projects, writing skills in mathematics and English are crucial. All projects should contain some research aspect, some challenge. There should be space for creativity and scientific
curiosity.

+ [FYP Website](https://hemu0626.github.io/Final-Year-Project/)

#### Summer Undergraduate Research Fellowship

+ SURF 2024: Survival Analysis in Poisoning [(Website)](https://hemu0626.github.io/first_quarto/)

+ SURF 2023: Elementary methods in Dimensionality Reduction and Transforms 

+ SURF 2022: Recent Developments in Psychometrical Methods [(Website)](https://hemu0626.github.io/educ_stat/) 